title: Ana Zappa
logo: docs/assets/ana_zappa.JPG
description: How action and social interaction shape second langauge learning
#show_downloads:true
theme: jekyll-theme-minimal

##Publications
-[upwork](https://scholar.google.com/citations?user=UqL-zFsAAAAJ&hl=fr)


